protocol = "vici-two-position"
doc = ""
traits = ["uses-uart", "uses-serial", "is-daemon", "has-position", "is-discrete"]
hardware = ["vici:e2ca", "vici:edma"]

[links]
source = "https://gitlab.com/yaq/yaqd-vici"
bugtracker = "https://gitlab.com/yaq/yaqd-vici/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-vici"
conda-forge = "https://anaconda.org/conda-forge/yaqd-vici"

[config]

[config.device_id]
doc = "VICI device ID, an integer from 0 to 9. If unspecified, will assume no ID. You must manually program your control modules with IDs, yaq will not attempt to apply IDs."
type = ["int", "null"]
default = "__null__"

[config.identifiers]
default = {"A"=0, "B"=1}
