protocol = "vici-two-position"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-vici"
bugtracker = "https://gitlab.com/yaq/yaqd-vici/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-vici"

[config]

[state]

[messages]

